openapi: 3.0.1
info:
  title: CreditMaestro API
  version: '1.0'
paths:
  /getTransactions:
    post:
      operationId: getTransactions
      summary: Get sandbox transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
              required: [startDate, endDate]
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
